### ISSUE TITLE
Do you have it published?

### ISSUE THREAD

**Issue by piranna** [NodeOS/nodeos-linux#1]
This would help to download the Linux kernel sources only once :-) Currently the build system is blazingly fast, but this would help too :-D

**Comment by joshgarde** [comment]
I was hoping to move it to the main NodeOS organization then publish

**Comment by piranna** [comment]
That's a good idea, we could later see how to integrate it. I was thinking to put the generic code of `nodeos-barebones` on its own project, so we could do both things at the same time, and later use it as a dependency of `nodeos-cross-toolchain` too.

**Comment by piranna** [comment]
New versions are being automatically published on npm thanks to `buho` and SemaphoreCI, clossing.
